# Generated by Django 6.1.1 on 2026-09-26 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fantrax_id', models.CharField(blank=True, max_length=16, null=True, unique=True)),
                ('positions', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('fantrax_id', models.CharField(blank=True, max_length=32, null=True, unique=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='FarmPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drafted_year', models.PositiveIntegerField()),
                ('salary', models.PositiveIntegerField()),
                ('salary_season', models.PositiveIntegerField(help_text='Season the salary applies to')),
                ('has_mlb_appearance', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('released', 'Released'), ('promoted', 'Promoted')], default='active', max_length=10)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='farm_stints', to='league.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='farm', to='league.team')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_price', models.PositiveIntegerField()),
                ('year_signed', models.PositiveIntegerField(help_text='League season that had just ended when signed')),
                ('length', models.PositiveIntegerField()),
                ('sign_and_trade', models.BooleanField(default=False, help_text='Counts under the sign-and-trade exception')),
                ('note', models.TextField(blank=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='league.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='league.team')),
            ],
            options={
                'ordering': ['team', 'player__name'],
            },
        ),
        migrations.CreateModel(
            name='CashTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_season', models.PositiveIntegerField()),
                ('amount', models.PositiveIntegerField()),
                ('note', models.CharField(blank=True, max_length=200)),
                ('from_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_sent', to='league.team')),
                ('to_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_received', to='league.team')),
            ],
        ),
        migrations.CreateModel(
            name='Buyout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dropped_in_season', models.PositiveIntegerField()),
                ('note', models.TextField(blank=True)),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='buyout', to='league.contract')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buyouts', to='league.team')),
            ],
        ),
        migrations.CreateModel(
            name='BudgetAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.PositiveIntegerField()),
                ('kind', models.CharField(choices=[('missed_ip', 'Missed IP penalty')], max_length=20)),
                ('amount', models.PositiveIntegerField()),
                ('note', models.CharField(blank=True, max_length=200)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='league.team')),
            ],
        ),
        migrations.CreateModel(
            name='TeamAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=100, unique=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='league.team')),
            ],
        ),
        migrations.CreateModel(
            name='FarmPick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('round', models.PositiveIntegerField()),
                ('original_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='league.team')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='farm_picks', to='league.team')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('year', 'round', 'original_team'), name='unique_farm_pick')],
            },
        ),
    ]
