# Generated by Django 6.1.1 on 2026-09-26 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReconciliationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.PositiveIntegerField()),
                ('kind', models.CharField(choices=[('continues', 'Continues'), ('expiring', 'Expiring'), ('traded', 'Traded (contract moves)'), ('dropped', 'Dropped (buyout owed)'), ('dropped_free', 'Dropped in final year (no penalty)'), ('inconsistent', 'Needs a look')], max_length=20)),
                ('detail', models.TextField(blank=True)),
                ('fantrax_tx_ids', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('decided_note', models.TextField(blank=True)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='league.contract')),
                ('team', models.ForeignKey(blank=True, help_text='New holder (trade) or team owing the buyout (drop)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='league.team')),
            ],
            options={
                'ordering': ['kind', 'contract__team__code'],
            },
        ),
    ]
