# Generated by Django 6.1.1 on 2026-09-26 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('discord_id', models.CharField(blank=True, help_text='Discord user ID (numeric), not the username', max_length=32, null=True, unique=True)),
                ('discord_username', models.CharField(blank=True, help_text='Last seen at sign-in', max_length=100)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='managers', to='league.team')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['team', 'name'],
            },
        ),
    ]
