# Generated by Django 6.1.1 on 2026-09-26 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0002_reconciliation_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='reconciliationitem',
            name='farm_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='league.farmplayer'),
        ),
        migrations.AddField(
            model_name='reconciliationitem',
            name='mlb_debut',
            field=models.BooleanField(default=False, help_text='Farm player appeared in MLB this season'),
        ),
        migrations.AddField(
            model_name='reconciliationitem',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='league.player'),
        ),
        migrations.AlterField(
            model_name='reconciliationitem',
            name='kind',
            field=models.CharField(choices=[('continues', 'Continues'), ('expiring', 'Expiring'), ('traded', 'Traded (contract moves)'), ('dropped', 'Dropped (buyout owed)'), ('dropped_free', 'Dropped in final year (no penalty)'), ('inconsistent', 'Needs a look'), ('farm_continues', 'Farm: still on the farm'), ('farm_traded', 'Farm: traded'), ('farm_promoted', "Farm: promoted (can't return)"), ('farm_released', 'Farm: released'), ('farm_inconsistent', 'Farm: needs a look'), ('farm_unknown', 'Farm: in Fantrax minors but not on the sheet')], max_length=20),
        ),
        migrations.AlterField(
            model_name='reconciliationitem',
            name='team',
            field=models.ForeignKey(blank=True, help_text='New holder (trade/promotion) or team owing the buyout (drop)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='league.team'),
        ),
    ]
