# Generated by Django 6.1.1 on 2026-09-26 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0002_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='is_commissioner',
            field=models.BooleanField(default=False, help_text='Full access to the admin, on top of the manager pages'),
        ),
    ]
