# Generated by Django 6.1.1 on 2026-09-26 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0003_farm_reconciliation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reconciliationitem',
            name='kind',
            field=models.CharField(choices=[('continues', 'Continues'), ('expiring', 'Expiring'), ('traded', 'Traded (contract moves)'), ('dropped', 'Dropped (buyout owed)'), ('dropped_free', 'Dropped in final year (no penalty)'), ('inconsistent', 'Needs a look'), ('farm_continues', 'Farm: still on the farm'), ('farm_traded', 'Farm: traded'), ('farm_promoted', "Farm: promoted (can't return)"), ('farm_released', 'Farm: released'), ('farm_inconsistent', 'Farm: needs a look'), ('farm_unknown', 'Farm: in Fantrax minors but not on the sheet'), ('cash_comment', 'Trade comment mentioning cash (enter a CashTrade by hand)')], max_length=20),
        ),
    ]
