# Generated by Django 6.1.1 on 2026-09-26 19:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0003_manager_is_commissioner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='discord_id',
            field=models.CharField(blank=True, help_text='Discord user ID (numeric), not the username', max_length=32, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d+$', 'A Discord user ID is all digits (not the username).')]),
        ),
    ]
