# Generated by Django 6.1.1 on 2026-09-26 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0004_cash_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='voided_in_season',
            field=models.PositiveIntegerField(blank=True, help_text='Dropped in its final year', null=True),
        ),
    ]
