# Generated by Django 6.1.1 on 2026-09-26 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0004_discord_id_digits'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SigningPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.PositiveIntegerField(help_text='The season that just ended', unique=True)),
                ('status', models.CharField(choices=[('planned', 'Not open yet'), ('open', 'Open'), ('locked', 'Locked')], default='planned', max_length=10)),
                ('deadline', models.DateTimeField(blank=True, help_text='Shown to managers; nothing locks automatically', null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuditEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(max_length=100)),
                ('detail', models.TextField(blank=True)),
                ('note', models.TextField(blank=True)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='league.team')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'audit entries',
                'ordering': ['-at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted')], default='draft', max_length=10)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='league.signingperiod')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='league.team')),
            ],
            options={
                'ordering': ['team'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionBuyout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='league.contract')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyouts', to='league.submission')),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionFarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keep', models.BooleanField()),
                ('farm_player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='league.farmplayer')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farm', to='league.submission')),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionSigning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.PositiveIntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='league.player')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signings', to='league.submission')),
            ],
        ),
        migrations.CreateModel(
            name='RosterEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.PositiveIntegerField(help_text='The season that just ended')),
                ('salary', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(help_text='Fantrax roster slot: Active, Reserve, IR, Minors', max_length=10)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='roster_entries', to='league.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='roster', to='league.team')),
            ],
            options={
                'ordering': ['team', 'player__name'],
                'constraints': [models.UniqueConstraint(fields=('season', 'player'), name='one_roster_spot_per_season')],
            },
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(fields=('period', 'team'), name='one_submission_per_team'),
        ),
        migrations.AddConstraint(
            model_name='submissionbuyout',
            constraint=models.UniqueConstraint(fields=('submission', 'contract'), name='buy_out_once'),
        ),
        migrations.AddConstraint(
            model_name='submissionfarm',
            constraint=models.UniqueConstraint(fields=('submission', 'farm_player'), name='decide_farm_once'),
        ),
        migrations.AddConstraint(
            model_name='submissionsigning',
            constraint=models.UniqueConstraint(fields=('submission', 'player'), name='sign_player_once'),
        ),
    ]
