# Generated by Django 6.1.1 on 2026-09-26 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0005_contract_voided'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashtrade',
            name='fantrax_tx_id',
            field=models.CharField(blank=True, help_text='Fantrax trade this cash was part of', max_length=32),
        ),
    ]
