# Generated by Django 6.1.1 on 2026-09-26 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0005_signing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='sign_and_trade',
            field=models.BooleanField(default=False, help_text='Record only: acquired by sign-and-trade'),
        ),
    ]
