# Generated by Django 6.1.1 on 2026-09-27 01:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0006_sign_and_trade_record_only'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FantraxLeague',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league_id', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('season', models.PositiveIntegerField(help_text='League season its moves belong to')),
                ('process_since', models.DateTimeField(blank=True, help_text='Ignore moves before this time (the league data already includes them)', null=True)),
                ('active', models.BooleanField(default=True, help_text='Read by Sync from Fantrax')),
            ],
            options={
                'ordering': ['season', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='FantraxEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=120, unique=True)),
                ('happened_at', models.DateTimeField()),
                ('kind', models.CharField(choices=[('TRADE', 'Trade'), ('DROP', 'Drop'), ('CLAIM', 'Claim'), ('PROMOTED', 'Promotion'), ('DEBUT', 'MLB debut'), ('DEBUT_CHECK', 'Possible MLB debut'), ('MINORS_UNKNOWN', 'Minors player not on a farm'), ('CASH_COMMENT', 'Cash in a trade comment'), ('ROSTER_MISMATCH', "Roster doesn't match")], max_length=20)),
                ('effect', models.CharField(choices=[('CONTRACT_MOVED', 'Contract moved'), ('BUYOUT', 'Buyout'), ('VOIDED', 'Contract voided'), ('FARM_MOVED', 'Farm moved'), ('FARM_RELEASED', 'Farm released'), ('FARM_PROMOTED', 'Farm promoted'), ('FARM_DEBUT', 'Farm debut'), ('ALREADY_REFLECTED', 'Already reflected'), ('NONE', 'No change'), ('EXCEPTION', 'Exception')], max_length=20)),
                ('fantrax_player_id', models.CharField(blank=True, max_length=32)),
                ('player_name', models.CharField(blank=True, max_length=100)),
                ('detail', models.TextField(blank=True)),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_note', models.TextField(blank=True)),
                ('buyout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='league.buyout')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='league.contract')),
                ('farm_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='league.farmplayer')),
                ('from_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='league.team')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='league.player')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('to_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='league.team')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='league.fantraxleague')),
            ],
            options={
                'ordering': ['-happened_at', 'pk'],
            },
        ),
    ]
