# Generated by Django 6.1.1 on 2026-09-27 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0007_fantrax_events'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReconciliationItem',
        ),
    ]
