# Generated by Django 6.1.1 on 2026-09-27 02:48

from datetime import datetime
from zoneinfo import ZoneInfo

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed(apps, schema_editor):
    """2026 is under way: its boundary is the cutoff the imported sheet already reflects."""
    Season = apps.get_model("league", "Season")
    start = datetime(2026, 2, 25, 16, 0, tzinfo=ZoneInfo("America/New_York"))
    Season.objects.get_or_create(year=2026, defaults={"auction_starts_at": start, "started_at": start})


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0009_seed_2026_fantrax_league'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True)),
                ('farm_draft_starts_at', models.DateTimeField(blank=True, help_text='Claims from here until the auction start are farm draft picks', null=True)),
                ('auction_starts_at', models.DateTimeField(help_text='Moves from here on belong to this season')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['year'],
            },
        ),
        migrations.RunPython(seed, migrations.RunPython.noop),
    ]
