# Generated by Django 6.1.1 on 2026-09-27 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0010_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmpick',
            name='player',
            field=models.ForeignKey(blank=True, help_text='Who the pick was spent on', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='league.player'),
        ),
        migrations.AlterField(
            model_name='fantraxevent',
            name='effect',
            field=models.CharField(choices=[('CONTRACT_MOVED', 'Contract moved'), ('BUYOUT', 'Buyout'), ('VOIDED', 'Contract voided'), ('FARM_MOVED', 'Farm moved'), ('FARM_RELEASED', 'Farm released'), ('FARM_PROMOTED', 'Farm promoted'), ('FARM_DEBUT', 'Farm debut'), ('FARM_DRAFTED', 'Farm drafted'), ('ALREADY_REFLECTED', 'Already reflected'), ('NONE', 'No change'), ('EXCEPTION', 'Exception')], max_length=20),
        ),
    ]
