# Generated by Django 6.1.1 on 2026-09-27 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0011_farm_draft'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.PositiveIntegerField()),
                ('base', models.PositiveIntegerField()),
                ('contracts', models.PositiveIntegerField()),
                ('buyouts', models.PositiveIntegerField()),
                ('farm', models.PositiveIntegerField()),
                ('missed_ip', models.PositiveIntegerField()),
                ('cash_net', models.IntegerField()),
                ('remaining', models.IntegerField()),
                ('frozen_at', models.DateTimeField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='frozen_budgets', to='league.team')),
            ],
            options={
                'ordering': ['season', 'team'],
                'constraints': [models.UniqueConstraint(fields=('season', 'team'), name='one_frozen_budget_per_season')],
            },
        ),
    ]
