# Generated by Django 6.1.1 on 2026-09-27 11:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0012_seasonbudget'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalStanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.PositiveIntegerField()),
                ('place', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(14)])),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='league.team')),
            ],
            options={
                'ordering': ['-season', 'place'],
                'constraints': [models.UniqueConstraint(fields=('season', 'team'), name='one_place_per_team'), models.UniqueConstraint(fields=('season', 'place'), name='one_team_per_place')],
            },
        ),
    ]
