# Generated by Django 6.1.1 on 2026-09-27 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0013_final_standing'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='finalstanding',
            name='one_team_per_place',
        ),
    ]
