# Generated by Django 6.1.1 on 2026-09-27 11:43

import django.db.models.deletion
from django.db import migrations, models


def seed_2026_ids(apps, schema_editor):
    """Team.fantrax_id holds the 2026 league's IDs. Later leagues get theirs from the sync."""
    FantraxLeague = apps.get_model("league", "FantraxLeague")
    FantraxTeam = apps.get_model("league", "FantraxTeam")
    Team = apps.get_model("league", "Team")
    league = FantraxLeague.objects.filter(league_id="p3z8zy75mgdm460o").first()
    if league:
        for team in Team.objects.exclude(fantrax_id=None):
            FantraxTeam.objects.get_or_create(league=league, team=team, defaults={"fantrax_team_id": team.fantrax_id})


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0014_places_can_swap'),
    ]

    operations = [
        migrations.CreateModel(
            name='FantraxTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fantrax_team_id', models.CharField(max_length=32)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='league.fantraxleague')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fantrax_teams', to='league.team')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('league', 'team'), name='one_fantrax_id_per_league')],
            },
        ),
        migrations.RunPython(seed_2026_ids, migrations.RunPython.noop),
    ]
