# Generated by Django 6.1.1 on 2026-10-03 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0015_fantrax_team'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=32, unique=True)),
                ('channel_id', models.CharField(max_length=32)),
                ('channel_name', models.CharField(max_length=100)),
                ('author_id', models.CharField(max_length=32)),
                ('author_name', models.CharField(blank=True, max_length=100)),
                ('posted_at', models.DateTimeField()),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('content', models.TextField(blank=True)),
                ('readable', models.TextField(blank=True, help_text='The text with @mentions shown as usernames')),
                ('has_attachments', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('CASH', 'Cash trade'), ('NOT_CASH', 'No cash'), ('IGNORED', 'Not a trade channel'), ('EXCEPTION', 'Exception')], max_length=10)),
                ('detail', models.TextField(blank=True)),
                ('synced_at', models.DateTimeField()),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_note', models.TextField(blank=True)),
                ('resolved_content', models.TextField(blank=True, help_text='The text when resolved; an edit reopens it')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-posted_at'],
            },
        ),
        migrations.AddField(
            model_name='cashtrade',
            name='discord_message',
            field=models.ForeignKey(blank=True, help_text='The #trades-<year>-assets post this came from (Sync from Discord)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_trades', to='league.discordmessage'),
        ),
    ]
