from django.contrib import admin, messages
from django.contrib.admin.options import ActionLocation
from django.db import DatabaseError

from league import models


@admin.register(models.Team)
class TeamAdmin(admin.ModelAdmin):
    list_display = ["code", "name", "fantrax_id"]


@admin.register(models.Manager)
class ManagerAdmin(admin.ModelAdmin):
    """Link a person to a team. They can sign in once their Discord ID is here."""

    list_display = ["name", "team", "discord_username", "discord_id", "user"]
    list_filter = ["team"]
    search_fields = ["name", "discord_username", "discord_id"]
    readonly_fields = ["discord_username", "user"]


@admin.register(models.Player)
class PlayerAdmin(admin.ModelAdmin):
    list_display = ["name", "fantrax_id", "positions"]
    search_fields = ["name", "fantrax_id"]


@admin.register(models.Contract)
class ContractAdmin(admin.ModelAdmin):
    list_display = ["player", "team", "original_price", "year_signed", "length", "sign_and_trade"]
    list_filter = ["team"]
    search_fields = ["player__name"]


@admin.register(models.Buyout)
class BuyoutAdmin(admin.ModelAdmin):
    list_display = ["contract", "team", "dropped_in_season"]
    list_filter = ["team"]


@admin.register(models.FarmPlayer)
class FarmPlayerAdmin(admin.ModelAdmin):
    list_display = ["player", "team", "drafted_year", "salary", "salary_season", "has_mlb_appearance", "status"]
    list_filter = ["team", "status"]


admin.site.register([models.TeamAlias, models.FarmPick, models.CashTrade, models.BudgetAdjustment])


@admin.register(models.ReconciliationItem)
class ReconciliationItemAdmin(admin.ModelAdmin):
    """Items are generated by `reconcile` and decided only through the actions. The only editable
    field is the note on a pending item, kept when it's accepted or rejected."""

    list_display = ["player", "contract", "kind", "team", "status", "detail"]
    list_filter = ["season", "kind", "status"]
    search_fields = ["player__name", "contract__player__name"]
    actions = ["accept_selected", "reject_selected"]

    def get_readonly_fields(self, request, obj=None):
        fields = [f.name for f in self.model._meta.fields]
        if obj is not None and obj.status == models.ReconciliationItem.Status.PENDING:
            fields.remove("decided_note")
        return fields

    def has_add_permission(self, request):
        return False

    def has_delete_permission(self, request, obj=None):
        # Deleting a decided item would erase the decision and let reconcile propose it again.
        return obj is None or obj.status == models.ReconciliationItem.Status.PENDING

    def get_actions(self, request, action_location=ActionLocation.CHANGE_LIST):
        actions = super().get_actions(request, action_location)
        actions.pop("delete_selected", None)
        return actions

    def _decide(self, request, queryset, verb, decide):
        done = 0
        for item in queryset.filter(status=models.ReconciliationItem.Status.PENDING):
            try:
                decide(item)  # each item is its own transaction
                done += 1
            except (ValueError, DatabaseError) as e:
                self.message_user(request, f"{item}: {e}", level=messages.ERROR)
        self.message_user(request, f"{verb} {done} item(s).")

    @admin.action(description="Accept selected (apply the change)")
    def accept_selected(self, request, queryset):
        self._decide(request, queryset, "Accepted", lambda i: i.accept(note=self._note(i, "Accepted", request)))

    @admin.action(description="Reject selected (no change)")
    def reject_selected(self, request, queryset):
        self._decide(request, queryset, "Rejected", lambda i: i.reject(note=self._note(i, "Rejected", request)))

    @staticmethod
    def _note(item, verb, request):
        return f"{verb} by {request.user}" + (f": {item.decided_note}" if item.decided_note else "")
